import type { Exercise, Muscle } from "./types";

function e(
  id: string,
  name: string,
  primary: Muscle,
  equipment: Exercise["equipment"],
  extra: Partial<Exercise> = {},
): Exercise {
  return {
    id,
    name,
    primary,
    secondary: [],
    equipment,
    mechanic: "isolation",
    defaultWeightLb: 20,
    incrementLb: 5,
    instructions: [],
    ...extra,
  };
}

/** Gym-standard lifts from Fitbod’s public exercise library that weren’t in the base catalog. */
export const EXTRA_EXERCISES: Exercise[] = [
  e("decline-bb-bench", "Decline Barbell Bench", "chest", ["barbell", "bench"], {
    secondary: ["triceps", "frontDelts"],
    mechanic: "compound",
    defaultWeightLb: 135,
    met: 6,
  }),
  e("decline-db-bench", "Decline Dumbbell Bench", "chest", ["dumbbell", "bench"], {
    secondary: ["triceps", "frontDelts"],
    mechanic: "compound",
    defaultWeightLb: 55,
    met: 6,
  }),
  e("floor-press", "Barbell Floor Press", "chest", ["barbell"], {
    secondary: ["triceps", "frontDelts"],
    mechanic: "compound",
    defaultWeightLb: 135,
    met: 6,
  }),
  e("db-floor-press", "Dumbbell Floor Press", "chest", ["dumbbell"], {
    secondary: ["triceps"],
    mechanic: "compound",
    defaultWeightLb: 55,
    met: 5.5,
  }),
  e("svend-press", "Svend Press", "chest", ["dumbbell"], { defaultWeightLb: 25, met: 4 }),
  e("db-squeeze-press", "Dumbbell Squeeze Press", "chest", ["dumbbell", "bench"], {
    secondary: ["triceps"],
    mechanic: "compound",
    defaultWeightLb: 40,
    met: 5,
  }),
  e("db-pullover", "Dumbbell Pullover", "chest", ["dumbbell", "bench"], {
    secondary: ["lats"],
    defaultWeightLb: 40,
    met: 4.5,
  }),
  e("cable-chest-press", "Cable Chest Press", "chest", ["cable"], {
    secondary: ["triceps", "frontDelts"],
    mechanic: "compound",
    defaultWeightLb: 40,
    met: 5,
  }),
  e("low-cable-fly", "Low Cable Fly", "chest", ["cable"], { defaultWeightLb: 20, met: 4 }),
  e("inc-db-fly", "Incline Dumbbell Fly", "chest", ["dumbbell", "bench"], { defaultWeightLb: 25, met: 4 }),
  e("decline-db-fly", "Decline Dumbbell Fly", "chest", ["dumbbell", "bench"], { defaultWeightLb: 25, met: 4 }),
  e("reverse-grip-bench", "Reverse-Grip Bench Press", "chest", ["barbell", "bench"], {
    secondary: ["triceps"],
    mechanic: "compound",
    defaultWeightLb: 115,
    met: 6,
  }),
  e("pause-bench", "Pause Bench Press", "chest", ["barbell", "bench"], {
    secondary: ["triceps", "frontDelts"],
    mechanic: "compound",
    defaultWeightLb: 135,
    met: 6,
  }),
  e("hand-release-pushup", "Hand-Release Push-Up", "chest", ["bodyweight"], {
    secondary: ["triceps", "frontDelts"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 8,
  }),
  e("incline-pushup", "Incline Push-Up", "chest", ["bodyweight"], {
    secondary: ["triceps"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 6,
  }),
  e("decline-pushup", "Decline Push-Up", "chest", ["bodyweight"], {
    secondary: ["frontDelts", "triceps"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 8,
  }),
  e("single-arm-cable-press", "Single-Arm Cable Press", "chest", ["cable"], {
    secondary: ["frontDelts"],
    mechanic: "compound",
    defaultWeightLb: 25,
    met: 5,
  }),

  e("hs-high-row", "Hammer Strength High Row", "lats", ["machine"], {
    secondary: ["upperBack", "biceps"],
    mechanic: "compound",
    defaultWeightLb: 90,
    met: 5.5,
  }),
  e("inc-db-row", "Incline Dumbbell Row", "upperBack", ["dumbbell", "bench"], {
    secondary: ["lats", "biceps"],
    mechanic: "compound",
    defaultWeightLb: 50,
    met: 5.5,
  }),
  e("kb-row", "Kettlebell Row", "lats", ["kettlebell"], {
    secondary: ["upperBack", "biceps"],
    mechanic: "compound",
    defaultWeightLb: 53,
    met: 6,
  }),
  e("landmine-row", "Landmine Row", "upperBack", ["barbell"], {
    secondary: ["lats", "biceps"],
    mechanic: "compound",
    defaultWeightLb: 90,
    met: 6,
  }),
  e("inverted-row", "Inverted Row", "upperBack", ["bodyweight"], {
    secondary: ["lats", "biceps"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 8,
  }),
  e("rev-grip-pulldown", "Reverse-Grip Pulldown", "lats", ["cable"], {
    secondary: ["biceps"],
    mechanic: "compound",
    defaultWeightLb: 80,
    met: 5.5,
  }),
  e("v-bar-pulldown", "V-Bar Pulldown", "lats", ["cable"], {
    secondary: ["biceps"],
    mechanic: "compound",
    defaultWeightLb: 90,
    met: 5.5,
  }),
  e("single-arm-pulldown", "Single-Arm Lat Pulldown", "lats", ["cable"], {
    secondary: ["biceps"],
    mechanic: "compound",
    defaultWeightLb: 40,
    met: 5,
  }),
  e("gorilla-row", "Gorilla Row", "lats", ["kettlebell"], {
    secondary: ["upperBack", "biceps"],
    mechanic: "compound",
    defaultWeightLb: 53,
    met: 6,
  }),
  e("renegade-row", "Renegade Row", "upperBack", ["dumbbell"], {
    secondary: ["lats", "abs", "triceps"],
    mechanic: "compound",
    defaultWeightLb: 40,
    met: 8,
  }),
  e("assisted-pullup", "Assisted Pull-Up", "lats", ["machine", "pullupBar"], {
    secondary: ["biceps"],
    mechanic: "compound",
    defaultWeightLb: 80,
    met: 6,
  }),
  e("wide-pullup", "Wide-Grip Pull-Up", "lats", ["pullupBar"], {
    secondary: ["upperBack", "biceps"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 8,
  }),
  e("mixed-pullup", "Mixed-Grip Pull-Up", "lats", ["pullupBar"], {
    secondary: ["biceps"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 8,
  }),
  e("muscle-up", "Muscle-Up", "lats", ["pullupBar"], {
    secondary: ["chest", "triceps", "frontDelts"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 9,
  }),
  e("dead-hang", "Dead Hang", "forearms", ["pullupBar"], {
    secondary: ["lats"],
    defaultWeightLb: 0,
    bodyweight: true,
    met: 3,
  }),
  e("medball-slam", "Medicine Ball Slam", "abs", ["bodyweight"], {
    secondary: ["lats", "frontDelts"],
    mechanic: "compound",
    defaultWeightLb: 20,
    met: 8,
  }),
  e("shotgun-row", "Shotgun Row", "lats", ["cable"], {
    secondary: ["upperBack"],
    mechanic: "compound",
    defaultWeightLb: 40,
    met: 5.5,
  }),

  e("push-press", "Push Press", "frontDelts", ["barbell"], {
    secondary: ["triceps", "quads"],
    mechanic: "compound",
    defaultWeightLb: 95,
    met: 6.5,
  }),
  e("landmine-press", "Landmine Press", "frontDelts", ["barbell"], {
    secondary: ["chest", "triceps"],
    mechanic: "compound",
    defaultWeightLb: 70,
    met: 5.5,
  }),
  e("cable-front-raise", "Cable Front Raise", "frontDelts", ["cable"], { defaultWeightLb: 20, met: 4 }),
  e("plate-front-raise", "Front Plate Raise", "frontDelts", ["bodyweight"], { defaultWeightLb: 25, met: 4 }),
  e("cable-rear-delt", "Cable Rear Delt Fly", "rearDelts", ["cable"], { defaultWeightLb: 15, met: 4 }),
  e("machine-reverse-fly", "Machine Reverse Fly", "rearDelts", ["machine"], { defaultWeightLb: 40, met: 4 }),
  e("seated-bb-ohp", "Seated Barbell Shoulder Press", "frontDelts", ["barbell", "bench"], {
    secondary: ["triceps", "sideDelts"],
    mechanic: "compound",
    defaultWeightLb: 95,
    met: 6,
  }),
  e("behind-cable-lat-raise", "Behind-the-Back Cable Lateral Raise", "sideDelts", ["cable"], {
    defaultWeightLb: 15,
    met: 4,
  }),
  e("kb-ohp", "Kettlebell Overhead Press", "frontDelts", ["kettlebell"], {
    secondary: ["triceps"],
    mechanic: "compound",
    defaultWeightLb: 53,
    met: 6,
  }),
  e("cable-shoulder-press", "Cable Shoulder Press", "frontDelts", ["cable"], {
    secondary: ["triceps"],
    mechanic: "compound",
    defaultWeightLb: 30,
    met: 5,
  }),
  e("pike-pushup", "Pike Push-Up", "frontDelts", ["bodyweight"], {
    secondary: ["triceps"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 8,
  }),
  e("hspu", "Handstand Push-Up", "frontDelts", ["bodyweight"], {
    secondary: ["triceps", "abs"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 8,
  }),
  e("battle-ropes", "Battle Ropes", "frontDelts", ["bodyweight"], {
    secondary: ["abs", "forearms"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 9.8,
  }),
  e("db-front-raise", "Dumbbell Front Raise", "frontDelts", ["dumbbell"], { defaultWeightLb: 15, met: 4 }),

  e("rope-pushdown", "Cable Rope Tricep Extension", "triceps", ["cable"], { defaultWeightLb: 40, met: 4.5 }),
  e("bench-dip", "Bench Dip", "triceps", ["bench"], {
    secondary: ["chest"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 6,
  }),
  e("tate-press", "Tate Press", "triceps", ["dumbbell", "bench"], { defaultWeightLb: 25, met: 4.5 }),
  e("machine-tri-ext", "Machine Tricep Extension", "triceps", ["machine"], { defaultWeightLb: 50, met: 4 }),
  e("machine-tri-dip", "Machine Tricep Dip", "triceps", ["machine"], {
    mechanic: "compound",
    defaultWeightLb: 80,
    met: 5,
  }),
  e("ez-oh-ext", "EZ-Bar Overhead Extension", "triceps", ["ezBar"], { defaultWeightLb: 50, met: 4.5 }),
  e("lateral-cable-ext", "Lateral Cable Tricep Extension", "triceps", ["cable"], { defaultWeightLb: 20, met: 4 }),
  e("one-arm-tri-side", "Cable One-Arm Side Extension", "triceps", ["cable"], { defaultWeightLb: 15, met: 4 }),
  e("inc-skull", "Incline Skull Crusher", "triceps", ["ezBar", "bench"], { defaultWeightLb: 50, met: 4.5 }),
  e("assisted-dip", "Assisted Dip", "triceps", ["machine", "dipStation"], {
    secondary: ["chest"],
    mechanic: "compound",
    defaultWeightLb: 80,
    met: 6,
  }),
  e("underhand-pushdown", "Cable Underhand Pushdown", "triceps", ["cable"], { defaultWeightLb: 40, met: 4.5 }),

  e("machine-bi-curl", "Machine Bicep Curl", "biceps", ["machine"], { defaultWeightLb: 50, met: 4 }),
  e("cross-hammer", "Cross-Body Hammer Curl", "biceps", ["dumbbell"], {
    secondary: ["forearms"],
    defaultWeightLb: 25,
    met: 4,
  }),
  e("spider-curl", "Spider Curl", "biceps", ["dumbbell", "bench"], { defaultWeightLb: 25, met: 4 }),
  e("reverse-curl", "Reverse Barbell Curl", "biceps", ["barbell"], {
    secondary: ["forearms"],
    defaultWeightLb: 40,
    met: 4,
  }),
  e("zottman", "Zottman Curl", "biceps", ["dumbbell"], {
    secondary: ["forearms"],
    defaultWeightLb: 20,
    met: 4,
  }),
  e("rope-hammer", "Cable Rope Hammer Curl", "biceps", ["cable"], {
    secondary: ["forearms"],
    defaultWeightLb: 30,
    met: 4,
  }),
  e("wide-bb-curl", "Wide-Grip Barbell Curl", "biceps", ["barbell"], { defaultWeightLb: 55, met: 4 }),
  e("waiter-curl", "Waiter Curl", "biceps", ["dumbbell"], { defaultWeightLb: 25, met: 4 }),
  e("inc-hammer", "Incline Hammer Curl", "biceps", ["dumbbell", "bench"], { defaultWeightLb: 25, met: 4 }),
  e("cable-preacher", "Cable Preacher Curl", "biceps", ["cable"], { defaultWeightLb: 30, met: 4 }),
  e("behind-cable-curl", "Behind-the-Back Cable Curl", "biceps", ["cable"], { defaultWeightLb: 25, met: 4 }),
  e("curl-21s", "Bicep 21s", "biceps", ["ezBar"], { defaultWeightLb: 40, met: 4.5 }),
  e("drag-curl", "Barbell Drag Curl", "biceps", ["barbell"], { defaultWeightLb: 50, met: 4 }),

  e("air-squat", "Air Squat", "quads", ["bodyweight"], {
    secondary: ["glutes"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 5.5,
  }),
  e("smith-squat", "Smith Machine Squat", "quads", ["smith"], {
    secondary: ["glutes"],
    mechanic: "compound",
    defaultWeightLb: 135,
    met: 6,
  }),
  e("zercher", "Zercher Squat", "quads", ["barbell"], {
    secondary: ["glutes", "abs"],
    mechanic: "compound",
    defaultWeightLb: 95,
    met: 6.5,
  }),
  e("box-squat", "Box Squat", "quads", ["barbell"], {
    secondary: ["glutes", "hamstrings"],
    mechanic: "compound",
    defaultWeightLb: 185,
    met: 6,
  }),
  e("wall-sit", "Wall Sit", "quads", ["bodyweight"], {
    defaultWeightLb: 0,
    bodyweight: true,
    met: 5,
  }),
  e("pistol", "Pistol Squat", "quads", ["bodyweight"], {
    secondary: ["glutes"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 8,
  }),
  e("reverse-lunge", "Reverse Lunge", "quads", ["dumbbell"], {
    secondary: ["glutes"],
    mechanic: "compound",
    defaultWeightLb: 40,
    met: 6,
  }),
  e("curtsy-lunge", "Curtsy Lunge", "glutes", ["dumbbell"], {
    secondary: ["quads"],
    mechanic: "compound",
    defaultWeightLb: 30,
    met: 5.5,
  }),
  e("side-lunge", "Side Lunge", "quads", ["dumbbell"], {
    secondary: ["adductors", "glutes"],
    mechanic: "compound",
    defaultWeightLb: 30,
    met: 5.5,
  }),
  e("oh-squat", "Overhead Squat", "quads", ["barbell"], {
    secondary: ["frontDelts", "abs"],
    mechanic: "compound",
    defaultWeightLb: 65,
    met: 6.5,
  }),
  e("jump-squat", "Jump Squat", "quads", ["bodyweight"], {
    secondary: ["glutes", "calves"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 8,
  }),
  e("burpee", "Burpee", "quads", ["bodyweight"], {
    secondary: ["chest", "abs"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 8,
  }),
  e("machine-squat", "Machine Squat", "quads", ["machine"], {
    secondary: ["glutes"],
    mechanic: "compound",
    defaultWeightLb: 180,
    met: 5.5,
  }),
  e("landmine-squat", "Landmine Squat", "quads", ["barbell"], {
    secondary: ["glutes"],
    mechanic: "compound",
    defaultWeightLb: 90,
    met: 6,
  }),
  e("split-squat", "Split Squat", "quads", ["dumbbell"], {
    secondary: ["glutes"],
    mechanic: "compound",
    defaultWeightLb: 40,
    met: 6,
  }),
  e("bb-lunge", "Barbell Lunge", "quads", ["barbell"], {
    secondary: ["glutes"],
    mechanic: "compound",
    defaultWeightLb: 95,
    met: 6,
  }),
  e("sled-push", "Sled Push", "quads", ["bodyweight"], {
    secondary: ["glutes", "calves"],
    mechanic: "compound",
    defaultWeightLb: 90,
    met: 8.5,
  }),

  e("stiff-dl", "Stiff-Legged Deadlift", "hamstrings", ["barbell"], {
    secondary: ["glutes", "lowerBack"],
    mechanic: "compound",
    defaultWeightLb: 135,
    met: 6,
  }),
  e("sl-rdl", "Single-Leg RDL", "hamstrings", ["dumbbell"], {
    secondary: ["glutes"],
    mechanic: "compound",
    defaultWeightLb: 40,
    met: 5.5,
  }),
  e("ghr", "Glute-Ham Raise", "hamstrings", ["bodyweight"], {
    secondary: ["glutes", "lowerBack"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 6.5,
  }),
  e("standing-leg-curl", "Standing Leg Curl", "hamstrings", ["machine"], { defaultWeightLb: 40, met: 4 }),
  e("snatch-grip-dl", "Snatch-Grip Deadlift", "hamstrings", ["barbell"], {
    secondary: ["upperBack", "glutes"],
    mechanic: "compound",
    defaultWeightLb: 185,
    met: 6.5,
  }),
  e("db-good-morning", "Dumbbell Good Morning", "hamstrings", ["dumbbell"], {
    secondary: ["glutes", "lowerBack"],
    mechanic: "compound",
    defaultWeightLb: 40,
    met: 5,
  }),

  e("db-hip-thrust", "Dumbbell Hip Thrust", "glutes", ["dumbbell", "bench"], {
    secondary: ["hamstrings"],
    mechanic: "compound",
    defaultWeightLb: 70,
    met: 5.5,
  }),
  e("cable-pull-through", "Cable Pull-Through", "glutes", ["cable"], {
    secondary: ["hamstrings"],
    mechanic: "compound",
    defaultWeightLb: 50,
    met: 5,
  }),
  e("frog-pump", "Frog Pump", "glutes", ["bodyweight"], {
    defaultWeightLb: 0,
    bodyweight: true,
    met: 4,
  }),
  e("cable-hip-ext", "Cable Hip Extension", "glutes", ["cable"], { defaultWeightLb: 30, met: 4.5 }),
  e("sl-hip-thrust", "Single-Leg Hip Thrust", "glutes", ["bodyweight", "bench"], {
    secondary: ["hamstrings"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 5.5,
  }),
  e("fire-hydrant", "Fire Hydrant", "glutes", ["bodyweight"], { defaultWeightLb: 0, bodyweight: true, met: 3.5 }),
  e("hip-abductor", "Hip Abductor Machine", "glutes", ["machine"], { defaultWeightLb: 80, met: 4 }),
  e("glute-kick-machine", "Glute Kickback Machine", "glutes", ["machine"], { defaultWeightLb: 50, met: 4.5 }),
  e("smith-hip-thrust", "Smith Machine Hip Thrust", "glutes", ["smith"], {
    secondary: ["hamstrings"],
    mechanic: "compound",
    defaultWeightLb: 135,
    met: 5.5,
  }),

  e("machine-calf", "Standing Machine Calf Raise", "calves", ["machine"], { defaultWeightLb: 100, met: 4 }),
  e("smith-calf", "Smith Machine Calf Raise", "calves", ["smith"], { defaultWeightLb: 135, met: 4 }),
  e("sl-calf", "Single-Leg Calf Raise", "calves", ["bodyweight"], {
    defaultWeightLb: 0,
    bodyweight: true,
    met: 4,
  }),
  e("seated-machine-calf", "Seated Machine Calf Press", "calves", ["machine"], { defaultWeightLb: 90, met: 4 }),

  e("crunch", "Crunch", "abs", ["bodyweight"], { defaultWeightLb: 0, bodyweight: true, met: 3.8 }),
  e("sit-up", "Sit-Up", "abs", ["bodyweight"], { defaultWeightLb: 0, bodyweight: true, met: 4 }),
  e("bicycle", "Bicycle Crunch", "abs", ["bodyweight"], {
    secondary: ["obliques"],
    defaultWeightLb: 0,
    bodyweight: true,
    met: 4.5,
  }),
  e("ab-crunch-machine", "Ab Crunch Machine", "abs", ["machine"], { defaultWeightLb: 70, met: 4 }),
  e("flutter-kick", "Flutter Kick", "abs", ["bodyweight"], { defaultWeightLb: 0, bodyweight: true, met: 4 }),
  e("reverse-crunch", "Reverse Crunch", "abs", ["bodyweight"], { defaultWeightLb: 0, bodyweight: true, met: 3.8 }),
  e("v-up", "V-Up", "abs", ["bodyweight"], { defaultWeightLb: 0, bodyweight: true, met: 4.5 }),
  e("toes-to-bar", "Toes to Bar", "abs", ["pullupBar"], {
    defaultWeightLb: 0,
    bodyweight: true,
    met: 6,
  }),
  e("cable-woodchop", "Cable Wood Chop", "obliques", ["cable"], { defaultWeightLb: 30, met: 5 }),
  e("cable-woodchop-low", "Cable Wood Chop (Low to High)", "obliques", ["cable"], { defaultWeightLb: 25, met: 5 }),
  e("cable-core-twist", "Standing Cable Core Twist", "obliques", ["cable"], { defaultWeightLb: 25, met: 4.5 }),
  e("side-plank", "Side Plank", "obliques", ["bodyweight"], { defaultWeightLb: 0, bodyweight: true, met: 3.8 }),
  e("bird-dog", "Bird Dog", "abs", ["bodyweight"], {
    secondary: ["lowerBack", "glutes"],
    defaultWeightLb: 0,
    bodyweight: true,
    met: 3.5,
  }),
  e("decline-situp", "Decline Sit-Up", "abs", ["bench"], { defaultWeightLb: 0, bodyweight: true, met: 4.5 }),
  e("windshield", "Windshield Wiper", "obliques", ["pullupBar"], {
    secondary: ["abs"],
    defaultWeightLb: 0,
    bodyweight: true,
    met: 5,
  }),
  e("db-side-bend", "Dumbbell Side Bend", "obliques", ["dumbbell"], { defaultWeightLb: 40, met: 4 }),
  e("l-sit", "L-Sit", "abs", ["bodyweight"], {
    secondary: ["quads"],
    defaultWeightLb: 0,
    bodyweight: true,
    met: 5,
  }),
  e("ball-crunch", "Exercise Ball Crunch", "abs", ["bodyweight"], { defaultWeightLb: 0, bodyweight: true, met: 3.8 }),
  e("leg-raise-floor", "Lying Leg Raise", "abs", ["bodyweight"], { defaultWeightLb: 0, bodyweight: true, met: 4 }),

  e("back-extension", "Back Extension", "lowerBack", ["bodyweight"], {
    secondary: ["glutes", "hamstrings"],
    mechanic: "compound",
    defaultWeightLb: 0,
    bodyweight: true,
    met: 4.5,
  }),
  e("superman", "Superman", "lowerBack", ["bodyweight"], {
    secondary: ["glutes"],
    defaultWeightLb: 0,
    bodyweight: true,
    met: 3.5,
  }),
  e("reverse-hyper", "Reverse Hyperextension", "lowerBack", ["machine"], {
    secondary: ["glutes"],
    mechanic: "compound",
    defaultWeightLb: 45,
    met: 5,
  }),
  e("seated-back-ext", "Seated Back Extension", "lowerBack", ["machine"], { defaultWeightLb: 80, met: 4 }),

  e("wrist-curl", "Wrist Curl", "forearms", ["barbell"], { defaultWeightLb: 35, incrementLb: 2.5, met: 3 }),
  e("reverse-wrist", "Reverse Wrist Curl", "forearms", ["barbell"], { defaultWeightLb: 25, incrementLb: 2.5, met: 3 }),

  e("hang-clean", "Hang Clean", "traps", ["barbell"], {
    secondary: ["quads", "glutes", "frontDelts"],
    mechanic: "compound",
    defaultWeightLb: 95,
    met: 6.5,
  }),
  e("clean-jerk", "Clean and Jerk", "quads", ["barbell"], {
    secondary: ["frontDelts", "traps", "triceps"],
    mechanic: "compound",
    defaultWeightLb: 95,
    met: 6.5,
  }),
  e("snatch", "Snatch", "quads", ["barbell"], {
    secondary: ["frontDelts", "traps", "hamstrings"],
    mechanic: "compound",
    defaultWeightLb: 75,
    met: 6.5,
  }),
  e("db-thruster", "Dumbbell Thruster", "quads", ["dumbbell"], {
    secondary: ["frontDelts", "triceps"],
    mechanic: "compound",
    defaultWeightLb: 40,
    met: 8,
  }),
];
