/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as LogRouteImport } from './routes/log'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as YouRouteImport } from './routes/you'
import { Route as ExercisesIdRouteImport } from './routes/exercises.$id'
import { Route as StatsIdRouteImport } from './routes/stats.$id'
import { Route as StravaCallbackRouteImport } from './routes/strava.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdRoute = ExercisesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExercisesRoute,
} as any)
const StatsIdRoute = StatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StatsRoute,
} as any)
const StravaCallbackRoute = StravaCallbackRouteImport.update({
  id: '/strava/callback',
  path: '/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/log': typeof LogRoute
  '/stats': typeof StatsRouteWithChildren
  '/you': typeof YouRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/stats/$id': typeof StatsIdRoute
  '/strava/callback': typeof StravaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/log': typeof LogRoute
  '/stats': typeof StatsRouteWithChildren
  '/you': typeof YouRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/stats/$id': typeof StatsIdRoute
  '/strava/callback': typeof StravaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/log': typeof LogRoute
  '/stats': typeof StatsRouteWithChildren
  '/you': typeof YouRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/stats/$id': typeof StatsIdRoute
  '/strava/callback': typeof StravaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises'
    | '/log'
    | '/stats'
    | '/you'
    | '/exercises/$id'
    | '/stats/$id'
    | '/strava/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises'
    | '/log'
    | '/stats'
    | '/you'
    | '/exercises/$id'
    | '/stats/$id'
    | '/strava/callback'
  id:
    | '__root__'
    | '/'
    | '/exercises'
    | '/log'
    | '/stats'
    | '/you'
    | '/exercises/$id'
    | '/stats/$id'
    | '/strava/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesRoute: typeof ExercisesRouteWithChildren
  LogRoute: typeof LogRoute
  StatsRoute: typeof StatsRouteWithChildren
  YouRoute: typeof YouRoute
  StravaCallbackRoute: typeof StravaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id': {
      id: '/exercises/$id'
      path: '/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof ExercisesIdRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/stats/$id': {
      id: '/stats/$id'
      path: '/$id'
      fullPath: '/stats/$id'
      preLoaderRoute: typeof StatsIdRouteImport
      parentRoute: typeof StatsRoute
    }
    '/strava/callback': {
      id: '/strava/callback'
      path: '/strava/callback'
      fullPath: '/strava/callback'
      preLoaderRoute: typeof StravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExercisesRouteChildren {
  ExercisesIdRoute: typeof ExercisesIdRoute
}

const ExercisesRouteChildren: ExercisesRouteChildren = {
  ExercisesIdRoute: ExercisesIdRoute,
}

const ExercisesRouteWithChildren = ExercisesRoute._addFileChildren(
  ExercisesRouteChildren,
)

interface StatsRouteChildren {
  StatsIdRoute: typeof StatsIdRoute
}

const StatsRouteChildren: StatsRouteChildren = {
  StatsIdRoute: StatsIdRoute,
}

const StatsRouteWithChildren = StatsRoute._addFileChildren(StatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesRoute: ExercisesRouteWithChildren,
  LogRoute: LogRoute,
  StatsRoute: StatsRouteWithChildren,
  YouRoute: YouRoute,
  StravaCallbackRoute: StravaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
